### ISSUE TITLE
Doesn't work as intended (needs an update?)

### ISSUE THREAD

**Issue by mike-lischke** [Microsoft/vscode-mock-debug#15]
I cloned the repo and played a bit with this extension. Adding a launch config works fine, but the `program` default value is something that seems to be broken. I left the default value as inserted by the "Add Configuration .." selector (`"${workspaceFolder}/Program"`) and tried to start debugging, which resulted in the message: "No such file or directory, open '<path>/Program'". Changing the `program` value to: `${workspaceFolder}/${command:AskForProgramName}` (which I guess is the intended value to be inserted there by default) asks me for a file name. After entering one (valid or not), nothing happens anymore. Same behavior, when I manually enter the path to a text file for `program` and started debugging again.

So, at the moment, the mock debug extension doesn't work and probably requires an overhaul (maybe do to latest vscode changes, no idea).

**Comment by weinand** [comment]
Yes, the default launch configuration for the "mock" debugger is less than ideal since it refers to a file "Program" (which a user probably doesn't have) and it does not include a `"stopOnEntry": true"` flag which makes the debugger quickly run through your "program" without stopping (so you won't see anything interesting).

Here is a better launch config which assumes that you have a non-empty file "readme.md" in your workspace:
```json
            {
                "type": "mock",
                "request": "launch",
                "name": "Ask for file name",
                "program": "${workspaceFolder}/readme.md",
                "stopOnEntry": true
            }
```

or this launch config which asks you for the name of an *.md file:
```json
            {
                "type": "mock",
                "request": "launch",
                "name": "Ask for file name",
                "program": "${workspaceFolder}/${command:AskForProgramName}",
                "stopOnEntry": true
            }
```

**Comment by mike-lischke** [comment]
Right, that makes sense. And now that I have some more insight I see that indeed something happens: the debugger is so quick, it's hard to see. When you set a breakpoint in the readme it stops however. `stopOnEntry` seems to be a good way to avoid confusion. Thanks for looking at that.

**Comment by weinand** [comment]
I've published a new version of mock-debug.
