### ISSUE TITLE
Setting required to use the c# debugger

### ISSUE THREAD

**Issue by jpwits** [microsoft/vscode-mock-debug#62]
Hi, this is not really an issue, but a question. I tested the mock debugger and it worked very well, just need to congratulate you for making this the easiest mock debugger I got working straight away.
Now the question, I have a specific requirement to create a project like this,  that then debugs a C# app and we can catch the info of the breakpoint in the main project app. What settings do I need to change though, to use the Omni C# debugger and not the Mock one.
Sorry I know this might be obvious, but I'm moving to vscode now after 30 years on visual studio, lol.

(Tried finding an example for this, but could not find one, I would love to spend some time on this topic, but can only afford to once I get it working)

Kind regards,
Jos Wilson

**Comment by weinand** [comment]
@jpwits I'm not sure that I understand your question...

What do you mean by "Omni C# debugger"? Is this an existing "VS Code debugger extension" or some other debugger where no VS Code integration exists?

**Comment by weinand** [comment]
@jpwits could you please help me understand your question? If not, I'll have to close the issue this week.

**Comment by jpwits** [comment]
Hi Andre,
Thanks for replying, what I actually wanted to do was to mock the debugger to go through each line of code, let say for some simple Console App, then use that info to draw up a sequence diagram of the code with values in place, this should give me the best of understanding another app quickly, but this seems to be a rather big challenge, so I'll give it another go sometime in the future.

**Comment by jpwits** [comment]
Hi Andre,
Also on this issue, I have struggle to figure out what generic structure is used for the C# language, so I could get the info from the debugger for a line of code, could also not get to mock c# itself.

**Comment by weinand** [comment]
@jpwits I think you misunderstood the purpose of "Mock Debug".
Mock Debug is the starting point for writing a new VS Code debug extension. It shows how implement the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) for a hypothetical debugger backend "MockRuntime".  "MockRuntime" is not a real debugger but just a very simple "simulation" of a debugger.

You cannot use this for your C# experiments/projects because you do not want to write a C# debugger (and Mock Debug by itself knows nothing about C#).

What you probably want is to use the existing C# debug extension and "spy" onto the communication between VS Code's generic debugger and the C# debug extension. This communication is based on the Debug Adapter Protocol (DAP) and is language and debugger independent. When "spying" on this you could probably find all the information you need for "drawing up a sequence diagram".

Spying on DAP is easy because VS Code provides API for this.

Here is a simple example:

TBD

**Comment by jpwits** [comment]
Hi,

Supper thanks Andre, an example for doing this, would be great, thanks.

**Comment by weinand** [comment]
You can find the example in my previous comment:

<img width="775" alt="CleanShot 2022-10-11 at 11 14 51@2x" src="https://user-images.githubusercontent.com/1898161/195049881-6d206db2-3959-4d35-87ce-a19ae3f8da8a.png">

**Comment by jpwits** [comment]
Thanks Andre, Yip I'm looking for an interactive code debugger, thus I want to keep track graphically of how the app creates and access all it's data, know the way, processing will come later. This was possible with VS in 2015, but can't find a way to do it now.
