### ISSUE TITLE
Step in and Step out

### ISSUE THREAD

**Issue by edencorbin** [Microsoft/vscode-mock-debug#7]
I am writing a custom debugger, and have break, as well as step over working, I'm having trouble implementing step in and step out, and wondering if there are functions in the mock debugger that trigger when these buttons are pressed, here's a stack overflow question I posted with the same issue: http://stackoverflow.com/questions/37779967/vscode-debugger-step-in-step-out

I appreciate your help on the matter.

**Comment by weinand** [comment]
@edencorbin 'mock debug' is just an educational debug adapter and I did not implemented `stepInRequest` and `stepOutRequest` because they would not add any new insights over the `nextRequest`.
If you want to implement them, just override the corresponding [methods](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/adapter/src/debugSession.ts#L499) of the base class `DebugSession`. They are called from the VS Code debugger UI.
It is not possible to disable the 'step in' and 'step out' buttons.

**Comment by edencorbin** [comment]
Okay great, I hand't look into the underlying methods of DebugSession, but will do so at this point, and I'm sure I can work from that, thanks for helping resolve this.
